-- lua/marvin/cmake_creator.lua
-- Interactive CMakeLists.txt wizard.
-- Generates a well-structured CMakeLists.txt for C or C++ projects,
-- with optional auto-link detection, test target (CTest + gtest/catch2),
-- and install rules.

local M = {}

local function ui() return require('marvin.ui') end
local function det() return require('marvin.detector') end
local function plain(it) return it.label end

-- ── Auto-link integration ─────────────────────────────────────────────────────
local function auto_detect_cmake_targets(root)
  local ok, cr = pcall(require, 'marvin.creator.cpp')
  if not ok then return {} end
  local ok2, d = pcall(require, 'marvin.detector')
  if not ok2 then return {} end
  local p = d.get()
  if not p then return {} end
  local links = cr.detect_links(p)
  return (links and links.cmake) or {}
end

-- ── Helpers ───────────────────────────────────────────────────────────────────
local function write(path, content, name)
  local f = io.open(path, 'w')
  if not f then
    vim.notify('[Marvin] Cannot write ' .. path, vim.log.levels.ERROR); return false
  end
  f:write(content); f:close()
  vim.cmd('edit ' .. vim.fn.fnameescape(path))
  vim.notify('[Marvin] CMakeLists.txt created for: ' .. name, vim.log.levels.INFO)
  return true
end

local function check_existing(path, content, name)
  if vim.fn.filereadable(path) == 1 then
    ui().select({
        { id = 'overwrite', label = 'Overwrite', desc = 'Replace existing CMakeLists.txt' },
        { id = 'cancel',    label = 'Cancel',    desc = 'Keep existing file' },
      }, { prompt = 'CMakeLists.txt already exists', format_item = plain },
      function(ch)
        if ch and ch.id == 'overwrite' then write(path, content, name) end
      end)
    return
  end
  write(path, content, name)
end

-- ── Template ──────────────────────────────────────────────────────────────────
local function cmake_template(opts)
  local lines = {}
  local function l(s) lines[#lines + 1] = (s or '') end

  local lang     = opts.lang == 'c' and 'C' or 'CXX'
  local std_var  = opts.lang == 'c' and 'CMAKE_C_STANDARD' or 'CMAKE_CXX_STANDARD'
  local std_req  = opts.lang == 'c' and 'CMAKE_C_STANDARD_REQUIRED' or 'CMAKE_CXX_STANDARD_REQUIRED'
  local std_ext  = opts.lang == 'c' and 'CMAKE_C_EXTENSIONS' or 'CMAKE_CXX_EXTENSIONS'
  local src_glob = opts.lang == 'c' and '*.c' or '*.cpp'
  local std_val  = opts.std or (opts.lang == 'c' and '11' or '17')

  -- Header
  l('# ' .. opts.name .. ' — generated by Marvin')
  l('# CMake ' .. (opts.cmake_min or '3.20') .. '+')
  l()
  l('cmake_minimum_required(VERSION ' .. (opts.cmake_min or '3.20') .. ')')
  l('project(' .. opts.name .. ' LANGUAGES ' .. lang .. ')')
  l()

  -- Language standard
  l('# ── Language standard ────────────────────────────────────────────────────')
  l('set(' .. std_var .. ' ' .. std_val .. ')')
  l('set(' .. std_req .. ' ON)')
  l('set(' .. std_ext .. ' OFF)')
  l()

  -- Source glob
  l('# ── Sources ──────────────────────────────────────────────────────────────')
  l('file(GLOB_RECURSE SOURCES CONFIGURE_DEPENDS')
  l('    "${CMAKE_CURRENT_SOURCE_DIR}/src/' .. src_glob .. '"')
  l(')')
  l()

  -- Executable
  l('# ── Target ───────────────────────────────────────────────────────────────')
  l('add_executable(' .. opts.name .. ' ${SOURCES})')
  l()

  -- Include dirs
  l('target_include_directories(' .. opts.name .. ' PRIVATE')
  l('    "${CMAKE_CURRENT_SOURCE_DIR}/include"')
  l(')')
  l()

  -- Compiler warnings
  l('# ── Compiler warnings ────────────────────────────────────────────────────')
  l('target_compile_options(' .. opts.name .. ' PRIVATE')
  if opts.lang == 'c' then
    l('    -Wall -Wextra -Wpedantic')
  else
    l('    -Wall -Wextra -Wpedantic -Wno-unused-parameter')
  end
  if opts.sanitizer and opts.sanitizer ~= 'none' then
    local sflag = opts.sanitizer == 'asan' and 'address'
        or opts.sanitizer == 'tsan' and 'thread'
        or 'undefined'
    l('    -fsanitize=' .. sflag .. ' -fno-omit-frame-pointer')
  end
  l(')')
  if opts.sanitizer and opts.sanitizer ~= 'none' then
    local sflag = opts.sanitizer == 'asan' and 'address'
        or opts.sanitizer == 'tsan' and 'thread'
        or 'undefined'
    l('target_link_options(' .. opts.name .. ' PRIVATE -fsanitize=' .. sflag .. ')')
  end
  l()

  -- Auto-detected + user libraries
  local all_targets = {}
  if opts.cmake_targets then
    for _, t in ipairs(opts.cmake_targets) do all_targets[#all_targets + 1] = t end
  end
  if opts.extra_libs and opts.extra_libs ~= '' then
    all_targets[#all_targets + 1] = opts.extra_libs
  end
  if #all_targets > 0 then
    l('# ── Link libraries ───────────────────────────────────────────────────────')
    -- Threading needs find_package
    local needs_threads = false
    for _, t in ipairs(all_targets) do
      if t:match('Threads') then needs_threads = true end
    end
    if needs_threads then
      l('find_package(Threads REQUIRED)')
    end
    l('target_link_libraries(' .. opts.name .. ' PRIVATE')
    for _, t in ipairs(all_targets) do
      l('    ' .. t)
    end
    l(')')
    l()
  end

  -- compile_commands.json
  l('# ── compile_commands.json (for clangd) ───────────────────────────────────')
  l('set(CMAKE_EXPORT_COMPILE_COMMANDS ON)')
  l()

  -- Optional: testing
  if opts.testing then
    l('# ── Tests ────────────────────────────────────────────────────────────────')
    l('enable_testing()')
    l()
    if opts.test_framework == 'gtest' then
      l('find_package(GTest REQUIRED)')
      l('file(GLOB_RECURSE TEST_SOURCES CONFIGURE_DEPENDS')
      l('    "${CMAKE_CURRENT_SOURCE_DIR}/tests/' .. src_glob .. '"')
      l(')')
      l('add_executable(' .. opts.name .. '_tests ${TEST_SOURCES})')
      l('target_include_directories(' .. opts.name .. '_tests PRIVATE')
      l('    "${CMAKE_CURRENT_SOURCE_DIR}/include"')
      l(')')
      l('target_link_libraries(' .. opts.name .. '_tests PRIVATE GTest::gtest_main)')
      l('include(GoogleTest)')
      l('gtest_discover_tests(' .. opts.name .. '_tests)')
    elseif opts.test_framework == 'catch2' then
      l('find_package(Catch2 3 REQUIRED)')
      l('file(GLOB_RECURSE TEST_SOURCES CONFIGURE_DEPENDS')
      l('    "${CMAKE_CURRENT_SOURCE_DIR}/tests/' .. src_glob .. '"')
      l(')')
      l('add_executable(' .. opts.name .. '_tests ${TEST_SOURCES})')
      l('target_include_directories(' .. opts.name .. '_tests PRIVATE')
      l('    "${CMAKE_CURRENT_SOURCE_DIR}/include"')
      l(')')
      l('target_link_libraries(' .. opts.name .. '_tests PRIVATE Catch2::Catch2WithMain)')
      l('include(CTest)')
      l('include(Catch)')
      l('catch_discover_tests(' .. opts.name .. '_tests)')
    else
      l('# add_subdirectory(tests)')
    end
    l()
  end

  -- Optional: install rules
  if opts.install then
    l('# ── Install ──────────────────────────────────────────────────────────────')
    l('install(TARGETS ' .. opts.name .. ' DESTINATION bin)')
    l('install(DIRECTORY include/ DESTINATION include)')
    l()
  end

  return table.concat(lines, '\n')
end

-- ── Wizard ────────────────────────────────────────────────────────────────────
function M.create(root, on_back)
  root = root or vim.fn.getcwd()
  local default_name = vim.fn.fnamemodify(root, ':t')

  -- Step 1: project name
  ui().input({ prompt = '󰬷 Project name', default = default_name }, function(name)
    if not name or name == '' then return end

    -- Step 2: language
    ui().select({
        { id = 'cpp', label = 'C++', desc = 'CXX language, .cpp sources' },
        { id = 'c',   label = 'C',   desc = 'C language, .c sources' },
      }, { prompt = 'Language', on_back = on_back, format_item = plain },
      function(lang_ch)
        if not lang_ch then return end
        local lang = lang_ch.id

        -- Step 3: standard
        local stds = lang == 'c'
            and {
              { id = '11', label = 'C11', desc = 'Recommended' },
              { id = '17', label = 'C17', desc = 'Latest stable' },
              { id = '99', label = 'C99', desc = 'Wide compat' },
            }
            or {
              { id = '17', label = 'C++17', desc = 'Recommended' },
              { id = '20', label = 'C++20', desc = 'Concepts, ranges' },
              { id = '23', label = 'C++23', desc = 'Latest' },
              { id = '14', label = 'C++14', desc = 'Lambdas, auto' },
            }
        ui().select(stds, { prompt = 'Standard', format_item = plain },
          function(std_ch)
            if not std_ch then return end

            -- Step 4: cmake minimum version
            ui().select({
                { id = '3.20', label = 'CMake 3.20', desc = 'Recommended minimum' },
                { id = '3.25', label = 'CMake 3.25', desc = 'Latest LTS features' },
                { id = '3.16', label = 'CMake 3.16', desc = 'Wide compatibility' },
              }, { prompt = 'CMake minimum version', format_item = plain },
              function(cmake_ch)
                if not cmake_ch then return end

                -- Step 5: sanitizer
                ui().select({
                    { id = 'none',  label = 'None' },
                    { id = 'asan',  label = 'AddressSanitizer', desc = '-fsanitize=address' },
                    { id = 'tsan',  label = 'ThreadSanitizer',  desc = '-fsanitize=thread' },
                    { id = 'ubsan', label = 'UBSanitizer',      desc = '-fsanitize=undefined' },
                  }, { prompt = 'Sanitizer (optional)', format_item = plain },
                  function(san_ch)
                    -- Step 6: testing
                    ui().select({
                        { id = 'none',   label = 'No tests' },
                        { id = 'gtest',  label = 'GoogleTest', desc = 'find_package(GTest)' },
                        { id = 'catch2', label = 'Catch2',     desc = 'find_package(Catch2 3)' },
                      }, { prompt = 'Test framework', format_item = plain },
                      function(test_ch)
                        -- Step 7: install rules
                        ui().select({
                            { id = 'yes', label = 'Yes — add install() rules' },
                            { id = 'no', label = 'No' },
                          }, { prompt = 'Add install rules?', format_item = plain },
                          function(inst_ch)
                            -- Auto-detect cmake link targets from existing includes
                            local cmake_targets = auto_detect_cmake_targets(root)
                            if #cmake_targets > 0 then
                              vim.notify(
                                '[Marvin] Auto-detected CMake targets:\n  '
                                .. table.concat(cmake_targets, '\n  '),
                                vim.log.levels.INFO)
                            end

                            -- Optional extra libs
                            ui().input({
                              prompt  = 'Extra link targets (space-separated, optional)',
                              default = '',
                            }, function(extra)
                              local opts = {
                                name           = name,
                                lang           = lang,
                                std            = std_ch.id,
                                cmake_min      = cmake_ch.id,
                                sanitizer      = san_ch and san_ch.id or 'none',
                                testing        = test_ch and test_ch.id ~= 'none',
                                test_framework = test_ch and test_ch.id or nil,
                                install        = inst_ch and inst_ch.id == 'yes',
                                cmake_targets  = cmake_targets,
                                extra_libs     = extra and extra ~= '' and extra or nil,
                              }
                              local content = cmake_template(opts)
                              check_existing(root .. '/CMakeLists.txt', content, name)
                            end)
                          end)
                      end)
                  end)
              end)
          end)
      end)
  end)
end

return M
