-- lua/marvin/makefile_creator.lua
-- Interactive wizard that generates a Makefile for C, C++, or generic projects.
-- Called from the Jason dashboard "Create" section or :JasonNewMakefile.

local M = {}

local ui = function() return require('marvin.ui') end

-- ── Templates ─────────────────────────────────────────────────────────────────

local function c_template(opts)
  local name  = opts.name
  local cc    = opts.compiler or 'gcc'
  local std   = opts.std or 'c11'
  local src   = opts.src or 'src'
  local inc   = opts.inc or 'include'
  local out   = opts.out or name
  local extra = opts.cflags or ''

  return table.concat({
    '# ' .. name .. ' — generated by Jason/Marvin',
    '',
    'CC      := ' .. cc,
    'CFLAGS  := -std=' .. std .. ' -Wall -Wextra -pedantic' .. (extra ~= '' and (' ' .. extra) or ''),
    'LDFLAGS :=',
    'LIBS    :=',
    '',
    'SRC_DIR := ' .. src,
    'INC_DIR := ' .. inc,
    'OBJ_DIR := build/obj',
    'BIN_DIR := build/bin',
    '',
    'TARGET  := $(BIN_DIR)/' .. out,
    'SRCS    := $(wildcard $(SRC_DIR)/*.c)',
    'OBJS    := $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SRCS))',
    '',
    '.PHONY: all clean test install dist',
    '',
    'all: $(TARGET)',
    '',
    '$(TARGET): $(OBJS) | $(BIN_DIR)',
    '\t$(CC) $(LDFLAGS) $^ -o $@ $(LIBS)',
    '',
    '$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)',
    '\t$(CC) $(CFLAGS) -I$(INC_DIR) -MMD -MP -c $< -o $@',
    '',
    '$(OBJ_DIR) $(BIN_DIR):',
    '\t@mkdir -p $@',
    '',
    '-include $(OBJS:.o=.d)',
    '',
    'clean:',
    '\t@rm -rf build/',
    '\t@echo "Cleaned."',
    '',
    'test:',
    '\t@echo "No tests configured yet."',
    '',
    'install: $(TARGET)',
    '\t@install -m 755 $(TARGET) /usr/local/bin/' .. out,
    '\t@echo "Installed to /usr/local/bin/' .. out .. '"',
    '',
    'dist: all',
    '\t@mkdir -p dist',
    '\t@cp $(TARGET) dist/',
    '\t@echo "Distribution ready in dist/"',
    '',
  }, '\n')
end

local function cpp_template(opts)
  local name  = opts.name
  local cxx   = opts.compiler or 'g++'
  local std   = opts.std or 'c++17'
  local src   = opts.src or 'src'
  local inc   = opts.inc or 'include'
  local out   = opts.out or name
  local extra = opts.cflags or ''

  return table.concat({
    '# ' .. name .. ' — generated by Jason/Marvin',
    '',
    'CXX     := ' .. cxx,
    'CXXFLAGS := -std=' .. std .. ' -Wall -Wextra -pedantic' .. (extra ~= '' and (' ' .. extra) or ''),
    'LDFLAGS :=',
    'LIBS    :=',
    '',
    'SRC_DIR := ' .. src,
    'INC_DIR := ' .. inc,
    'OBJ_DIR := build/obj',
    'BIN_DIR := build/bin',
    '',
    'TARGET  := $(BIN_DIR)/' .. out,
    'SRCS    := $(wildcard $(SRC_DIR)/*.cpp)',
    'OBJS    := $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(SRCS))',
    '',
    '.PHONY: all clean test install dist',
    '',
    'all: $(TARGET)',
    '',
    '$(TARGET): $(OBJS) | $(BIN_DIR)',
    '\t$(CXX) $(LDFLAGS) $^ -o $@ $(LIBS)',
    '',
    '$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp | $(OBJ_DIR)',
    '\t$(CXX) $(CXXFLAGS) -I$(INC_DIR) -MMD -MP -c $< -o $@',
    '',
    '$(OBJ_DIR) $(BIN_DIR):',
    '\t@mkdir -p $@',
    '',
    '-include $(OBJS:.o=.d)',
    '',
    'clean:',
    '\t@rm -rf build/',
    '\t@echo "Cleaned."',
    '',
    'test:',
    '\t@echo "No tests configured yet."',
    '',
    'install: $(TARGET)',
    '\t@install -m 755 $(TARGET) /usr/local/bin/' .. out,
    '\t@echo "Installed to /usr/local/bin/' .. out .. '"',
    '',
    'dist: all',
    '\t@mkdir -p dist',
    '\t@cp $(TARGET) dist/',
    '\t@echo "Distribution ready in dist/"',
    '',
  }, '\n')
end

local function generic_template(opts)
  local name = opts.name
  return table.concat({
    '# ' .. name .. ' — generated by Jason/Marvin',
    '',
    '.PHONY: all build test clean install dist',
    '',
    'all: build',
    '',
    'build:',
    '\t@echo "Add your build command here"',
    '',
    'test:',
    '\t@echo "Add your test command here"',
    '',
    'clean:',
    '\t@echo "Add your clean command here"',
    '',
    'install:',
    '\t@echo "Add your install command here"',
    '',
    'dist:',
    '\t@echo "Add your dist command here"',
    '',
  }, '\n')
end

-- ── Wizard steps ──────────────────────────────────────────────────────────────

-- Step 4: write the file and open it
local function write_and_open(content, root, opts)
  local path = root .. '/Makefile'

  -- Warn if one already exists
  if vim.fn.filereadable(path) == 1 then
    ui().select({
        { id = 'overwrite', label = 'Overwrite', desc = 'Replace the existing Makefile' },
        { id = 'cancel',    label = 'Cancel',    desc = 'Keep the existing file' },
      }, { prompt = 'Makefile already exists', format_item = function(it) return it.label end },
      function(choice)
        if choice and choice.id == 'overwrite' then
          M._write(path, content, opts.name)
        end
      end)
    return
  end

  M._write(path, content, opts.name)
end

function M._write(path, content, name)
  local f = io.open(path, 'w')
  if not f then
    vim.notify('[Jason] Failed to write Makefile: ' .. path, vim.log.levels.ERROR); return
  end
  f:write(content); f:close()
  vim.cmd('edit ' .. vim.fn.fnameescape(path))
  vim.notify('[Jason] Makefile created for: ' .. name, vim.log.levels.INFO)
end

-- Step 3 (C/C++): optional flags → generate
local function step_flags(opts, root, lang)
  ui().input({
    prompt  = 'Extra compiler flags (optional)',
    default = opts.debug and '-g -O0' or '-O2',
  }, function(flags)
    opts.cflags = (flags ~= '' and flags or nil)
    local content = lang == 'c' and c_template(opts) or cpp_template(opts)
    write_and_open(content, root, opts)
  end)
end

-- Step 2b (C/C++): pick C/C++ standard
local function step_std(opts, root, lang)
  local standards = lang == 'c'
      and {
        { id = 'c11', label = 'C11', desc = 'Recommended modern standard' },
        { id = 'c17', label = 'C17', desc = 'Latest stable' },
        { id = 'c99', label = 'C99', desc = 'Wide compatibility' },
        { id = 'c89', label = 'C89', desc = 'Maximum compatibility' },
      }
      or {
        { id = 'c++17', label = 'C++17', desc = 'Recommended — structured bindings, if constexpr' },
        { id = 'c++20', label = 'C++20', desc = 'Concepts, ranges, coroutines' },
        { id = 'c++14', label = 'C++14', desc = 'Lambdas, auto' },
        { id = 'c++11', label = 'C++11', desc = 'Move semantics, smart pointers' },
      }

  ui().select(standards, {
    prompt      = 'Language Standard',
    format_item = function(it) return it.label end,
  }, function(choice)
    if not choice then return end
    opts.std = choice.id
    step_flags(opts, root, lang)
  end)
end

-- Step 2a (C/C++): pick compiler
local function step_compiler(opts, root, lang)
  local compilers = lang == 'c'
      and {
        { id = 'gcc',   label = 'gcc',   desc = 'GNU C Compiler (recommended)' },
        { id = 'clang', label = 'clang', desc = 'LLVM Clang' },
        { id = 'cc',    label = 'cc',    desc = 'System default' },
      }
      or {
        { id = 'g++',     label = 'g++',     desc = 'GNU C++ Compiler (recommended)' },
        { id = 'clang++', label = 'clang++', desc = 'LLVM Clang++' },
        { id = 'c++',     label = 'c++',     desc = 'System default' },
      }

  ui().select(compilers, {
    prompt      = 'Compiler',
    format_item = function(it) return it.label end,
  }, function(choice)
    if not choice then return end
    opts.compiler = choice.id
    step_std(opts, root, lang)
  end)
end

-- Step 1: project name + output binary, then branch by language
local function step_name(lang, root, on_back)
  local proj_root = root or vim.fn.getcwd()
  local default   = vim.fn.fnamemodify(proj_root, ':t')

  ui().input({ prompt = '󰬷 Project Name', default = default }, function(name)
    if not name or name == '' then return end

    ui().input({ prompt = '󰐊 Output Binary Name', default = name }, function(out)
      if not out or out == '' then out = name end

      local opts = { name = name, out = out }

      if lang == 'generic' then
        write_and_open(generic_template(opts), proj_root, opts)
      else
        step_compiler(opts, proj_root, lang)
      end
    end)
  end)
end

-- ── Entry point: language picker ──────────────────────────────────────────────
function M.create(root, on_back)
  root = root or vim.fn.getcwd()

  ui().select({
    { id = 'cpp', label = '󰙲 C++', desc = 'g++ / clang++, wildcard *.cpp sources' },
    { id = 'c', label = '󰙱 C', desc = 'gcc / clang, wildcard *.c sources' },
    { id = 'generic', label = '󰈙 Generic', desc = 'Skeleton with all, build, test, clean, install, dist' },
  }, {
    prompt      = 'Makefile Type',
    on_back     = on_back,
    format_item = function(it) return it.label end,
  }, function(choice)
    if not choice then return end
    vim.cmd('stopinsert')
    vim.schedule(function() step_name(choice.id, root, on_back) end)
  end)
end

return M
