-- lua/marvin/makefile_creator.lua
-- Universal interactive Makefile wizard.
-- Supports: C, C++, Go, Rust, and Generic projects.
-- For C/C++: integrates auto-link detection from marvin.creator.cpp.
-- Called from any language dashboard, :JasonNewMakefile, :MarvinNewMakefile.

local M = {}

local ui = function() return require('marvin.ui') end

-- ── Language detection helper ─────────────────────────────────────────────────
-- Infer the best Makefile language from the current project, or ask.
local function infer_lang(root)
  -- Check for Cargo.toml → Rust wrapper Makefile
  if vim.fn.filereadable(root .. '/Cargo.toml') == 1 then return 'rust' end
  -- Check for go.mod → Go wrapper Makefile
  if vim.fn.filereadable(root .. '/go.mod') == 1 then return 'go' end
  -- Heuristic: .cpp / .cxx / .cc files → C++; .c files → C
  local cpp_files = vim.fn.globpath(root, '**/*.cpp', false, true)
  local cxx_files = vim.fn.globpath(root, '**/*.cxx', false, true)
  local c_files   = vim.fn.globpath(root, '**/*.c', false, true)
  if #cpp_files > 0 or #cxx_files > 0 then return 'cpp' end
  if #c_files > 0 then return 'c' end
  return nil -- unknown
end

-- ── Auto-link integration ─────────────────────────────────────────────────────
-- Returns LDFLAGS string detected from project includes, or '' if unavailable.
local function auto_detect_ldflags(root)
  local ok, cr = pcall(require, 'marvin.creator.cpp')
  if not ok then return '' end
  local ok2, det = pcall(require, 'marvin.detector')
  if not ok2 then return '' end
  local p = det.get()
  if not p then return '' end
  local links = cr.detect_links(p)
  return (links and links.ldflags) or ''
end

-- ── Shared helpers ────────────────────────────────────────────────────────────
local function write_makefile(path, content, name)
  local f = io.open(path, 'w')
  if not f then
    vim.notify('[Marvin] Failed to write Makefile: ' .. path, vim.log.levels.ERROR); return false
  end
  f:write(content); f:close()
  vim.cmd('edit ' .. vim.fn.fnameescape(path))
  vim.notify('[Marvin] Makefile created for: ' .. name, vim.log.levels.INFO)
  return true
end

local function check_existing(path, content, opts, root)
  if vim.fn.filereadable(path) == 1 then
    ui().select({
        { id = 'overwrite', label = 'Overwrite', desc = 'Replace the existing Makefile' },
        { id = 'cancel',    label = 'Cancel',    desc = 'Keep the existing file' },
      }, { prompt = 'Makefile already exists', format_item = function(it) return it.label end },
      function(choice)
        if choice and choice.id == 'overwrite' then
          write_makefile(path, content, opts.name)
        end
      end)
    return
  end
  write_makefile(path, content, opts.name)
end

-- ══════════════════════════════════════════════════════════════════════════════
-- TEMPLATES
-- ══════════════════════════════════════════════════════════════════════════════

-- ── C template ────────────────────────────────────────────────────────────────
local function c_template(opts)
  local name       = opts.name
  local cc         = opts.compiler or 'gcc'
  local std        = opts.std or 'c11'
  local src        = opts.src or 'src'
  local inc        = opts.inc or 'include'
  local out        = opts.out or name
  local extra      = opts.cflags or ''
  local lflags     = opts.ldflags or ''
  local libs       = opts.libs or ''

  -- Combine auto-detected + user ldflags
  local all_lflags = vim.trim(lflags .. ' ' .. libs)

  return table.concat({
    '# ' .. name .. ' — generated by Marvin',
    '#',
    '# Usage:',
    '#   make          Build the binary',
    '#   make test     Run tests (add test runner)',
    '#   make clean    Remove build artefacts',
    '#   make install  Install to /usr/local/bin',
    '#   make dist     Copy binary to dist/',
    '',
    'CC      := ' .. cc,
    'CFLAGS  := -std=' .. std .. ' -Wall -Wextra -pedantic'
    .. (extra ~= '' and (' ' .. extra) or ''),
    'LDFLAGS := ' .. (all_lflags ~= '' and all_lflags or ''),
    '',
    'SRC_DIR := ' .. src,
    'INC_DIR := ' .. inc,
    'OBJ_DIR := build/obj',
    'BIN_DIR := build/bin',
    '',
    'TARGET  := $(BIN_DIR)/' .. out,
    'SRCS    := $(wildcard $(SRC_DIR)/*.c)',
    'OBJS    := $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SRCS))',
    'DEPS    := $(OBJS:.o=.d)',
    '',
    '.PHONY: all clean test install dist',
    '',
    'all: $(TARGET)',
    '',
    '$(TARGET): $(OBJS) | $(BIN_DIR)',
    '\t$(CC) $^ -o $@ $(LDFLAGS)',
    '',
    '$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)',
    '\t$(CC) $(CFLAGS) -I$(INC_DIR) -MMD -MP -c $< -o $@',
    '',
    '-include $(DEPS)',
    '',
    '$(OBJ_DIR) $(BIN_DIR):',
    '\t@mkdir -p $@',
    '',
    'clean:',
    '\t@rm -rf build/',
    '\t@echo "Cleaned."',
    '',
    'test:',
    '\t@echo "No test runner configured. Add your test command here."',
    '',
    'install: $(TARGET)',
    '\t@install -m 755 $(TARGET) /usr/local/bin/' .. out,
    '\t@echo "Installed → /usr/local/bin/' .. out .. '"',
    '',
    'dist: all',
    '\t@mkdir -p dist',
    '\t@cp $(TARGET) dist/',
    '\t@echo "Distribution ready in dist/"',
    '',
  }, '\n')
end

-- ── C++ template ──────────────────────────────────────────────────────────────
local function cpp_template(opts)
  local name       = opts.name
  local cxx        = opts.compiler or 'g++'
  local std        = opts.std or 'c++17'
  local src        = opts.src or 'src'
  local inc        = opts.inc or 'include'
  local out        = opts.out or name
  local extra      = opts.cflags or ''
  local lflags     = opts.ldflags or ''
  local libs       = opts.libs or ''

  local all_lflags = vim.trim(lflags .. ' ' .. libs)

  -- Optional sanitizer support
  local san_flags  = ''
  if opts.sanitizer == 'asan' then
    san_flags = ' -fsanitize=address -fno-omit-frame-pointer'
  elseif opts.sanitizer == 'tsan' then
    san_flags = ' -fsanitize=thread'
  elseif opts.sanitizer == 'ubsan' then
    san_flags = ' -fsanitize=undefined'
  end

  -- compile_commands.json generation (via bear or intercept-build)
  local cc_json_section = opts.compile_commands and table.concat({
    '',
    'compile_commands:',
    '\t@if command -v bear >/dev/null 2>&1; then \\',
    '\t  bear -- $(MAKE) all; \\',
    '\telse \\',
    '\t  echo "install bear for compile_commands.json"; \\',
    '\tfi',
  }, '\n') or ''

  return table.concat({
    '# ' .. name .. ' — generated by Marvin',
    '#',
    '# Usage:',
    '#   make                 Build the binary',
    '#   make test            Run tests',
    '#   make clean           Remove build artefacts',
    '#   make install         Install to /usr/local/bin',
    '#   make dist            Copy binary to dist/',
    opts.compile_commands and '#   make compile_commands  Regenerate compile_commands.json (requires bear)' or '',
    '',
    'CXX      := ' .. cxx,
    'CXXFLAGS := -std=' .. std .. ' -Wall -Wextra -pedantic'
    .. (extra ~= '' and (' ' .. extra) or '')
    .. san_flags,
    'LDFLAGS  := ' .. (all_lflags ~= '' and all_lflags or ''),
    '',
    'SRC_DIR  := ' .. src,
    'INC_DIR  := ' .. inc,
    'OBJ_DIR  := build/obj',
    'BIN_DIR  := build/bin',
    '',
    'TARGET   := $(BIN_DIR)/' .. out,
    'SRCS     := $(wildcard $(SRC_DIR)/*.cpp)',
    'OBJS     := $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(SRCS))',
    'DEPS     := $(OBJS:.o=.d)',
    '',
    '.PHONY: all clean test install dist' .. (opts.compile_commands and ' compile_commands' or ''),
    '',
    'all: $(TARGET)',
    '',
    '$(TARGET): $(OBJS) | $(BIN_DIR)',
    '\t$(CXX) $^ -o $@ $(LDFLAGS)',
    '',
    '$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp | $(OBJ_DIR)',
    '\t$(CXX) $(CXXFLAGS) -I$(INC_DIR) -MMD -MP -c $< -o $@',
    '',
    '-include $(DEPS)',
    '',
    '$(OBJ_DIR) $(BIN_DIR):',
    '\t@mkdir -p $@',
    '',
    'clean:',
    '\t@rm -rf build/',
    '\t@echo "Cleaned."',
    '',
    'test:',
    '\t@echo "No test runner configured. Add your test command here."',
    '',
    'install: $(TARGET)',
    '\t@install -m 755 $(TARGET) /usr/local/bin/' .. out,
    '\t@echo "Installed → /usr/local/bin/' .. out .. '"',
    '',
    'dist: all',
    '\t@mkdir -p dist',
    '\t@cp $(TARGET) dist/',
    '\t@echo "Distribution ready in dist/"',
    cc_json_section,
    '',
  }, '\n')
end

-- ── Go wrapper Makefile ───────────────────────────────────────────────────────
local function go_template(opts)
  local name   = opts.name
  local mod    = opts.module or '.'
  local out    = opts.out or name
  local gofmt  = opts.formatter or 'gofmt'
  local linter = opts.linter or 'golangci-lint'

  return table.concat({
    '# ' .. name .. ' — generated by Marvin (Go)',
    '#',
    '# Usage:',
    '#   make          Build binary',
    '#   make test     Run tests',
    '#   make lint     Run linter',
    '#   make fmt      Format source',
    '#   make clean    Remove build artefacts',
    '#   make install  Install binary to GOPATH/bin',
    '',
    'BINARY   := ' .. out,
    'MODULE   := ' .. mod,
    'GOFLAGS  :=',
    'LDFLAGS  := -ldflags="-s -w"',
    '',
    'BUILD_DIR := build',
    '',
    '.PHONY: all build test lint fmt clean install tidy race cover',
    '',
    'all: build',
    '',
    'build:',
    '\t@mkdir -p $(BUILD_DIR)',
    '\tgo build $(GOFLAGS) $(LDFLAGS) -o $(BUILD_DIR)/$(BINARY) .',
    '',
    'test:',
    '\tgo test ./...',
    '',
    'race:',
    '\tgo test -race ./...',
    '',
    'cover:',
    '\tgo test -cover -coverprofile=coverage.out ./...',
    '\tgo tool cover -html=coverage.out -o coverage.html',
    '\t@echo "Coverage report: coverage.html"',
    '',
    'lint:',
    '\t' .. linter .. ' run ./...',
    '',
    'fmt:',
    '\t' .. gofmt .. ' -w .',
    '',
    'tidy:',
    '\tgo mod tidy',
    '',
    'clean:',
    '\t@rm -rf $(BUILD_DIR) coverage.out coverage.html',
    '\t@echo "Cleaned."',
    '',
    'install:',
    '\tgo install .',
    '\t@echo "Installed $(BINARY) to GOPATH/bin"',
    '',
  }, '\n')
end

-- ── Rust wrapper Makefile ─────────────────────────────────────────────────────
local function rust_template(opts)
  local name    = opts.name
  local profile = opts.profile or 'dev'
  local out     = opts.out or name

  local pflag   = profile == 'release' and '--release' or ''
  local pdir    = profile == 'release' and 'release' or 'debug'

  return table.concat({
    '# ' .. name .. ' — generated by Marvin (Rust/Cargo)',
    '#',
    '# Usage:',
    '#   make            Build (' .. profile .. ' profile)',
    '#   make test       Run tests',
    '#   make clippy     Lint with Clippy',
    '#   make fmt        Format with rustfmt',
    '#   make clean      cargo clean',
    '#   make release    Force release build',
    '#   make run        Build & run',
    '',
    'CARGO    := cargo',
    'PROFILE  := ' .. profile,
    'PFLAG    := ' .. pflag,
    'BIN      := target/' .. pdir .. '/' .. out,
    '',
    '.PHONY: all build test clippy fmt clean release run doc bench',
    '',
    'all: build',
    '',
    'build:',
    '\t$(CARGO) build $(PFLAG)',
    '',
    'run: build',
    '\t./$(BIN)',
    '',
    'test:',
    '\t$(CARGO) test',
    '',
    'clippy:',
    '\t$(CARGO) clippy -- -D warnings',
    '',
    'fmt:',
    '\t$(CARGO) fmt',
    '',
    'doc:',
    '\t$(CARGO) doc --open',
    '',
    'bench:',
    '\t$(CARGO) bench',
    '',
    'clean:',
    '\t$(CARGO) clean',
    '\t@echo "Cleaned."',
    '',
    'release:',
    '\t$(CARGO) build --release',
    '',
    'install:',
    '\t$(CARGO) install --path .',
    '',
  }, '\n')
end

-- ── Generic Makefile ──────────────────────────────────────────────────────────
local function generic_template(opts)
  local name = opts.name
  return table.concat({
    '# ' .. name .. ' — generated by Marvin',
    '#',
    '# Edit the targets below to fit your project.',
    '',
    '.PHONY: all build test clean install dist',
    '',
    'all: build',
    '',
    'build:',
    '\t@echo "Add your build command here"',
    '',
    'test:',
    '\t@echo "Add your test command here"',
    '',
    'clean:',
    '\t@echo "Add your clean command here"',
    '',
    'install:',
    '\t@echo "Add your install command here"',
    '',
    'dist:',
    '\t@echo "Add your dist command here"',
    '',
  }, '\n')
end

-- ══════════════════════════════════════════════════════════════════════════════
-- WIZARD STEPS
-- ══════════════════════════════════════════════════════════════════════════════

-- ── Step: extra CFLAGS ────────────────────────────────────────────────────────
local function step_cflags(opts, root, lang, ldflags_hint)
  local default = opts.debug and '-g -O0' or '-O2'
  ui().input({
    prompt  = 'Extra compiler flags (optional)',
    default = default,
  }, function(flags)
    opts.cflags = (flags and flags ~= '' and flags or nil)

    -- Ask about sanitizers for C/C++
    if lang == 'cpp' then
      ui().select({
          { id = 'none',  label = 'None',             desc = 'No sanitizer' },
          { id = 'asan',  label = 'AddressSanitizer', desc = '-fsanitize=address' },
          { id = 'tsan',  label = 'ThreadSanitizer',  desc = '-fsanitize=thread' },
          { id = 'ubsan', label = 'UBSanitizer',      desc = '-fsanitize=undefined' },
        }, { prompt = 'Sanitizer (optional)', format_item = function(it) return it.label end },
        function(san)
          opts.sanitizer = (san and san.id ~= 'none') and san.id or nil

          -- Ask about compile_commands.json
          ui().select({
              { id = 'yes', label = 'Yes — add compile_commands target', desc = 'requires bear' },
              { id = 'no', label = 'No' },
            }, { prompt = 'Add compile_commands.json target?', format_item = function(it) return it.label end },
            function(cc)
              opts.compile_commands = cc and cc.id == 'yes'
              -- Inject auto-detected LDFLAGS
              opts.ldflags = ldflags_hint
              local content = cpp_template(opts)
              check_existing(root .. '/Makefile', content, opts, root)
            end)
        end)
    else
      opts.ldflags = ldflags_hint
      local content = c_template(opts)
      check_existing(root .. '/Makefile', content, opts, root)
    end
  end)
end

-- ── Step: C standard ─────────────────────────────────────────────────────────
local function step_c_std(opts, root)
  ui().select({
      { id = 'c11', label = 'C11', desc = 'Recommended modern standard' },
      { id = 'c17', label = 'C17', desc = 'Latest stable' },
      { id = 'c99', label = 'C99', desc = 'Wide compatibility' },
      { id = 'c89', label = 'C89', desc = 'Maximum compatibility' },
    }, { prompt = 'C Standard', format_item = function(it) return it.label end },
    function(choice)
      if not choice then return end
      opts.std = choice.id
      step_cflags(opts, root, 'c', '')
    end)
end

-- ── Step: C++ standard ───────────────────────────────────────────────────────
local function step_cpp_std(opts, root, ldflags_hint)
  ui().select({
      { id = 'c++17', label = 'C++17', desc = 'Recommended — structured bindings, if constexpr' },
      { id = 'c++20', label = 'C++20', desc = 'Concepts, ranges, coroutines' },
      { id = 'c++23', label = 'C++23', desc = 'Latest (compiler support varies)' },
      { id = 'c++14', label = 'C++14', desc = 'Lambdas, auto' },
      { id = 'c++11', label = 'C++11', desc = 'Move semantics, smart pointers' },
    }, { prompt = 'C++ Standard', format_item = function(it) return it.label end },
    function(choice)
      if not choice then return end
      opts.std = choice.id
      step_cflags(opts, root, 'cpp', ldflags_hint)
    end)
end

-- ── Step: compiler ────────────────────────────────────────────────────────────
local function step_compiler(opts, root, lang, ldflags_hint)
  local compilers = lang == 'c'
      and {
        { id = 'gcc',   label = 'gcc',   desc = 'GNU C Compiler (recommended)' },
        { id = 'clang', label = 'clang', desc = 'LLVM Clang' },
        { id = 'cc',    label = 'cc',    desc = 'System default' },
      }
      or {
        { id = 'g++',     label = 'g++',     desc = 'GNU C++ Compiler (recommended)' },
        { id = 'clang++', label = 'clang++', desc = 'LLVM Clang++' },
        { id = 'c++',     label = 'c++',     desc = 'System default' },
      }

  ui().select(compilers, { prompt = 'Compiler', format_item = function(it) return it.label end },
    function(choice)
      if not choice then return end
      opts.compiler = choice.id
      if lang == 'c' then
        step_c_std(opts, root)
      else
        step_cpp_std(opts, root, ldflags_hint)
      end
    end)
end

-- ── Step: project name + binary ───────────────────────────────────────────────
local function step_name_binary(lang, root, on_back)
  local default = vim.fn.fnamemodify(root, ':t')

  ui().input({ prompt = '󰬷 Project Name', default = default }, function(name)
    if not name or name == '' then return end

    ui().input({ prompt = '󰐊 Output Binary Name', default = name }, function(out)
      if not out or out == '' then out = name end

      local opts = { name = name, out = out }

      if lang == 'generic' then
        check_existing(root .. '/Makefile', generic_template(opts), opts, root)
      elseif lang == 'go' then
        -- Ask module path
        local mod_default = 'github.com/yourname/' .. name
        local go_mod = root .. '/go.mod'
        if vim.fn.filereadable(go_mod) == 1 then
          for _, line in ipairs(vim.fn.readfile(go_mod)) do
            local m = line:match('^module%s+(%S+)')
            if m then
              mod_default = m; break
            end
          end
        end
        ui().input({ prompt = 'Module path', default = mod_default }, function(mod)
          opts.module = mod
          ui().select({
              { id = 'gofmt',     label = 'gofmt',     desc = 'Standard library formatter' },
              { id = 'goimports', label = 'goimports', desc = 'gofmt + import management' },
            }, { prompt = 'Formatter', format_item = function(it) return it.label end },
            function(fmt)
              opts.formatter = fmt and fmt.id or 'gofmt'
              check_existing(root .. '/Makefile', go_template(opts), opts, root)
            end)
        end)
      elseif lang == 'rust' then
        -- Read binary name from Cargo.toml if possible
        local cargo_toml = root .. '/Cargo.toml'
        if vim.fn.filereadable(cargo_toml) == 1 then
          for _, line in ipairs(vim.fn.readfile(cargo_toml)) do
            local n = line:match('^name%s*=%s*"([^"]+)"')
            if n then
              opts.out = n; break
            end
          end
        end
        ui().select({
            { id = 'dev',     label = 'dev (debug)', desc = 'Fast compilation, debug symbols' },
            { id = 'release', label = 'release',     desc = 'Optimised binary' },
          }, { prompt = 'Default profile', format_item = function(it) return it.label end },
          function(prof)
            opts.profile = prof and prof.id or 'dev'
            check_existing(root .. '/Makefile', rust_template(opts), opts, root)
          end)
      else
        -- C or C++: run auto-link detection first
        local ldflags_hint = ''
        if lang == 'cpp' or lang == 'c' then
          ldflags_hint = auto_detect_ldflags(root)
          if ldflags_hint ~= '' then
            vim.notify(
              '[Marvin] Auto-detected LDFLAGS: ' .. ldflags_hint
              .. '\nThese will be pre-filled in the Makefile.',
              vim.log.levels.INFO)
          end
        end
        step_compiler(opts, root, lang, ldflags_hint)
      end
    end)
  end)
end

-- ── Source/include dir detection ──────────────────────────────────────────────
local function step_dirs(lang, root, on_back)
  -- Suggest dirs based on what exists
  local has_src = vim.fn.isdirectory(root .. '/src') == 1
  local has_inc = vim.fn.isdirectory(root .. '/include') == 1

  if lang ~= 'c' and lang ~= 'cpp' then
    -- Go/Rust/generic don't need this
    step_name_binary(lang, root, on_back)
    return
  end

  local src_default = has_src and 'src' or '.'
  local inc_default = has_inc and 'include' or (has_src and 'src' or '.')

  ui().input({ prompt = 'Source directory', default = src_default }, function(src)
    src = (src and src ~= '') and src or src_default
    ui().input({ prompt = 'Include directory', default = inc_default }, function(inc)
      inc = (inc and inc ~= '') and inc or inc_default
      -- Stash so step_name_binary can pick them up
      -- We pass them via a small upvalue trick: redefine step_name_binary for this call
      local orig = step_name_binary
      step_name_binary = function(lg, rt, ob)
        step_name_binary = orig -- restore
        local default = vim.fn.fnamemodify(rt, ':t')
        ui().input({ prompt = '󰬷 Project Name', default = default }, function(name)
          if not name or name == '' then return end
          ui().input({ prompt = '󰐊 Output Binary Name', default = name }, function(out)
            if not out or out == '' then out = name end
            local opts = { name = name, out = out, src = src, inc = inc }
            local ldflags_hint = auto_detect_ldflags(rt)
            if ldflags_hint ~= '' then
              vim.notify('[Marvin] Auto-detected LDFLAGS: ' .. ldflags_hint, vim.log.levels.INFO)
            end
            step_compiler(opts, rt, lg, ldflags_hint)
          end)
        end)
      end
      step_name_binary(lang, root, on_back)
    end)
  end)
end

-- ══════════════════════════════════════════════════════════════════════════════
-- ENTRY POINT
-- ══════════════════════════════════════════════════════════════════════════════

-- Public entry point. root = project root dir, on_back = optional callback.
function M.create(root, on_back)
  root = root or vim.fn.getcwd()

  -- Try to pre-select language from project
  local detected_lang = infer_lang(root)

  local lang_items = {
    { id = 'cpp', label = '󰙲 C++', desc = 'g++/clang++, wildcard *.cpp sources, auto-link detection' },
    { id = 'c', label = '󰙱 C', desc = 'gcc/clang, wildcard *.c sources, auto-link detection' },
    { id = 'go', label = '󰟓 Go', desc = 'go build wrapper with test, lint, fmt, cover targets' },
    { id = 'rust', label = '󱘗 Rust', desc = 'cargo wrapper with clippy, fmt, doc, bench targets' },
    { id = 'generic', label = '󰈙 Generic', desc = 'Minimal skeleton: all, build, test, clean, install, dist' },
  }

  -- Move detected language to the top as a suggestion
  local prompt = 'Makefile Type'
  if detected_lang then
    prompt = 'Makefile Type  (detected: ' .. detected_lang .. ')'
    for i, it in ipairs(lang_items) do
      if it.id == detected_lang then
        table.remove(lang_items, i)
        table.insert(lang_items, 1, vim.tbl_extend('force', it, {
          label = it.label .. '  ✓ detected',
        }))
        break
      end
    end
  end

  ui().select(lang_items, {
    prompt      = prompt,
    on_back     = on_back,
    format_item = function(it) return it.label end,
  }, function(choice)
    if not choice then return end
    vim.cmd('stopinsert')
    vim.schedule(function()
      step_dirs(choice.id, root, on_back)
    end)
  end)
end

return M
